using ClosedXML.Excel;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using System.Data;

// DrawingML namespaces – aliased to avoid conflicts
using A   = DocumentFormat.OpenXml.Drawing;
using C   = DocumentFormat.OpenXml.Drawing.Charts;
using XDr = DocumentFormat.OpenXml.Drawing.Spreadsheet;

namespace LibraryManagementSystem.Helpers
{
    public static class ExcelHelper
    {
        private const string CompanyName    = "Graced Public Library";
        private const string CompanyAddress = "Buenavista, Irosin, Sorsogon";

        // Strongly-typed chart descriptor – avoids all static field scoping issues
        private sealed record ChartInfo(
            string     SheetName,
            string     Title,
            string[]   SeriesNames,
            string[]   Categories,
            double[][] Values);

        // ════════════════════════════════════════════════════════════════════
        //  SHARED HEADER / STYLING
        // ════════════════════════════════════════════════════════════════════

        private static void WriteHeader(IXLWorksheet ws, string reportTitle)
        {
            ws.Cell(1, 1).Value = CompanyName;
            ws.Cell(1, 1).Style.Font.Bold      = true;
            ws.Cell(1, 1).Style.Font.FontSize  = 18;
            ws.Cell(1, 1).Style.Font.FontColor = XLColor.FromHtml("#1a3c5e");
            ws.Range(1, 1, 1, 6).Merge();

            ws.Cell(2, 1).Value = CompanyAddress;
            ws.Cell(2, 1).Style.Font.Italic   = true;
            ws.Cell(2, 1).Style.Font.FontSize = 10;
            ws.Range(2, 1, 2, 6).Merge();

            ws.Cell(3, 1).Value = reportTitle;
            ws.Cell(3, 1).Style.Font.Bold      = true;
            ws.Cell(3, 1).Style.Font.FontSize  = 13;
            ws.Cell(3, 1).Style.Font.FontColor = XLColor.FromHtml("#2e6da4");
            ws.Range(3, 1, 3, 6).Merge();

            ws.Cell(4, 1).Value =
                $"Generated: {DateTime.Now:MMMM dd, yyyy HH:mm}   |   " +
                $"Generated by: {SessionHelper.FullName}";
            ws.Cell(4, 1).Style.Font.FontSize = 9;
            ws.Cell(4, 1).Style.Font.Italic   = true;
            ws.Range(4, 1, 4, 6).Merge();

            var logo = ws.Range(1, 7, 4, 8);
            logo.Merge();
            logo.FirstCell().Value = "[LIBRARY LOGO]";
            logo.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            logo.Style.Alignment.Vertical   = XLAlignmentVerticalValues.Center;
            logo.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
            logo.Style.Font.Italic          = true;
            logo.Style.Font.FontColor       = XLColor.Gray;

            ws.Row(5).Height = 6;
        }

        private static void WriteSignatureBlock(IXLWorksheet ws, int startRow, int cols)
        {
            startRow += 3;

            ws.Cell(startRow,     1).Value = "Prepared by:";
            ws.Cell(startRow + 1, 1).Value = SessionHelper.FullName;
            ws.Cell(startRow + 1, 1).Style.Font.Bold = true;
            ws.Cell(startRow + 2, 1).Value = $"({SessionHelper.Role})";

            ws.Range(startRow + 3, 1, startRow + 3, 3)
              .Style.Border.BottomBorder = XLBorderStyleValues.Thin;

            ws.Cell(startRow + 4, 1).Value = "Signature over Printed Name";
            ws.Cell(startRow + 4, 1).Style.Font.Italic   = true;
            ws.Cell(startRow + 4, 1).Style.Font.FontSize = 9;

            int col = Math.Max(1, cols - 1);
            ws.Cell(startRow,     col).Value = "Noted/Approved by:";
            ws.Cell(startRow + 1, col).Value = "_________________________";
            ws.Cell(startRow + 2, col).Value = "(Library Director)";
            ws.Cell(startRow + 2, col).Style.Font.Italic = true;
        }

        private static void StyleDataTable(IXLWorksheet ws, int hdrRow, int lastCol, int lastDataRow)
        {
            var hdr = ws.Range(hdrRow, 1, hdrRow, lastCol);
            hdr.Style.Fill.BackgroundColor = XLColor.FromHtml("#1a3c5e");
            hdr.Style.Font.FontColor       = XLColor.White;
            hdr.Style.Font.Bold            = true;
            hdr.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

            for (int r = hdrRow + 1; r <= lastDataRow; r++)
                if ((r - hdrRow) % 2 == 0)
                    ws.Range(r, 1, r, lastCol).Style.Fill.BackgroundColor =
                        XLColor.FromHtml("#eaf1fb");

            ws.Range(hdrRow, 1, lastDataRow, lastCol)
              .Style.Border.OutsideBorder = XLBorderStyleValues.Medium;
            ws.Range(hdrRow, 1, lastDataRow, lastCol)
              .Style.Border.InsideBorder  = XLBorderStyleValues.Hair;
        }

        // ════════════════════════════════════════════════════════════════════
        //  1. BORROWINGS REPORT
        // ════════════════════════════════════════════════════════════════════

        public static string GenerateBorrowingsReport(System.Data.DataTable dt, string savePath)
        {
            ChartInfo chartInfo;

            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Borrowings Report");
                WriteHeader(ws, "Borrowings Transaction Report");

                int hdrRow = 6;
                string[] cols = { "Borrowing ID", "Book Title", "Borrower", "Borrow Date", "Due Date", "Return Date", "Fine (PHP)" };
                for (int c = 0; c < cols.Length; c++)
                    ws.Cell(hdrRow, c + 1).Value = cols[c];

                int dataRow = hdrRow + 1;
                foreach (DataRow row in dt.Rows)
                {
                    ws.Cell(dataRow, 1).Value = row["borrowing_id"]?.ToString();
                    ws.Cell(dataRow, 2).Value = row["title"]?.ToString();
                    ws.Cell(dataRow, 3).Value = row["borrower"]?.ToString();
                    ws.Cell(dataRow, 4).Value = row["borrow_date"]?.ToString();
                    ws.Cell(dataRow, 5).Value = row["due_date"]?.ToString();
                    ws.Cell(dataRow, 6).Value = string.IsNullOrEmpty(row["return_date"]?.ToString())
                        ? "Not Returned" : row["return_date"]!.ToString();
                    ws.Cell(dataRow, 7).Value = Convert.ToDecimal(row["fine_amount"] ?? 0);
                    ws.Cell(dataRow, 7).Style.NumberFormat.Format = "#,##0.00";
                    dataRow++;
                }

                int lastData = dataRow - 1;
                StyleDataTable(ws, hdrRow, cols.Length, lastData);
                ws.Cell(lastData + 1, 6).Value    = "Total Fine:";
                ws.Cell(lastData + 1, 6).Style.Font.Bold = true;
                ws.Cell(lastData + 1, 7).FormulaA1 = $"=SUM(G{hdrRow + 1}:G{lastData})";
                ws.Cell(lastData + 1, 7).Style.NumberFormat.Format = "#,##0.00";
                ws.Cell(lastData + 1, 7).Style.Font.Bold = true;
                ws.Columns().AdjustToContents();
                WriteSignatureBlock(ws, lastData + 1, cols.Length);

                chartInfo = AddChartDataSheet(wb, "Borrowings Chart",
                    "Fine Amounts per Borrower",
                    new[] { "Fine (PHP)" },
                    dt,
                    row => (row["borrower"]?.ToString() ?? "",
                            new[] { Convert.ToDouble(row["fine_amount"] ?? 0) }));

                wb.SaveAs(savePath);
            }

            InjectChart(savePath, chartInfo);
            return savePath;
        }

        // ════════════════════════════════════════════════════════════════════
        //  2. BOOKS INVENTORY REPORT
        // ════════════════════════════════════════════════════════════════════

        public static string GenerateBooksReport(System.Data.DataTable dt, string savePath)
        {
            ChartInfo chartInfo;

            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Books Inventory");
                WriteHeader(ws, "Books Inventory Report");

                int hdrRow = 6;
                string[] cols = { "Book ID", "Title", "Author", "ISBN", "Total Copies", "Available", "Borrowed" };
                for (int c = 0; c < cols.Length; c++)
                    ws.Cell(hdrRow, c + 1).Value = cols[c];

                int dataRow = hdrRow + 1;
                foreach (DataRow row in dt.Rows)
                {
                    int total     = Convert.ToInt32(row["total_copies"]     ?? 0);
                    int available = Convert.ToInt32(row["available_copies"] ?? 0);
                    ws.Cell(dataRow, 1).Value = row["book_id"]?.ToString();
                    ws.Cell(dataRow, 2).Value = row["title"]?.ToString();
                    ws.Cell(dataRow, 3).Value = row["author"]?.ToString();
                    ws.Cell(dataRow, 4).Value = row["isbn"]?.ToString();
                    ws.Cell(dataRow, 5).Value = total;
                    ws.Cell(dataRow, 6).Value = available;
                    ws.Cell(dataRow, 7).Value = total - available;
                    dataRow++;
                }

                int lastData = dataRow - 1;
                StyleDataTable(ws, hdrRow, cols.Length, lastData);
                ws.Columns().AdjustToContents();
                WriteSignatureBlock(ws, lastData + 1, cols.Length);

                chartInfo = AddChartDataSheet(wb, "Inventory Chart",
                    "Book Inventory: Available vs Borrowed",
                    new[] { "Available", "Borrowed" },
                    dt,
                    row =>
                    {
                        int tot = Convert.ToInt32(row["total_copies"]     ?? 0);
                        int avl = Convert.ToInt32(row["available_copies"] ?? 0);
                        return (row["title"]?.ToString() ?? "",
                                new[] { (double)avl, (double)(tot - avl) });
                    });

                wb.SaveAs(savePath);
            }

            InjectChart(savePath, chartInfo);
            return savePath;
        }

        // ════════════════════════════════════════════════════════════════════
        //  3. USER ACTIVITY REPORT
        // ════════════════════════════════════════════════════════════════════

        public static string GenerateUserActivityReport(System.Data.DataTable dt, string savePath)
        {
            ChartInfo chartInfo;

            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("User Activity");
                WriteHeader(ws, "User Activity Report");

                int hdrRow = 6;
                string[] cols = { "User ID", "Full Name", "Username", "Role", "Status", "Total Borrowings", "Active Loans", "Total Fines (PHP)" };
                for (int c = 0; c < cols.Length; c++)
                    ws.Cell(hdrRow, c + 1).Value = cols[c];

                int dataRow = hdrRow + 1;
                foreach (DataRow row in dt.Rows)
                {
                    ws.Cell(dataRow, 1).Value = row["user_id"]?.ToString();
                    ws.Cell(dataRow, 2).Value = row["full_name"]?.ToString();
                    ws.Cell(dataRow, 3).Value = row["username"]?.ToString();
                    ws.Cell(dataRow, 4).Value = row["role"]?.ToString();
                    ws.Cell(dataRow, 5).Value = row["status"]?.ToString();
                    ws.Cell(dataRow, 6).Value = Convert.ToInt32(row["total_borrowings"] ?? 0);
                    ws.Cell(dataRow, 7).Value = Convert.ToInt32(row["active_loans"]     ?? 0);
                    ws.Cell(dataRow, 8).Value = Convert.ToDecimal(row["total_fines"]    ?? 0);
                    ws.Cell(dataRow, 8).Style.NumberFormat.Format = "#,##0.00";
                    dataRow++;
                }

                int lastData = dataRow - 1;
                StyleDataTable(ws, hdrRow, cols.Length, lastData);
                ws.Columns().AdjustToContents();
                WriteSignatureBlock(ws, lastData + 1, cols.Length);

                chartInfo = AddChartDataSheet(wb, "Activity Chart",
                    "User Activity: Borrowings and Fines",
                    new[] { "Borrowings", "Fines (PHP)" },
                    dt,
                    row => (row["full_name"]?.ToString() ?? "",
                            new[]
                            {
                                Convert.ToDouble(row["total_borrowings"] ?? 0),
                                Convert.ToDouble(row["total_fines"]      ?? 0)
                            }));

                wb.SaveAs(savePath);
            }

            InjectChart(savePath, chartInfo);
            return savePath;
        }

        // ════════════════════════════════════════════════════════════════════
        //  CHART DATA SHEET  (ClosedXML pass – writes Sheet 2 data rows)
        // ════════════════════════════════════════════════════════════════════

        private static ChartInfo AddChartDataSheet(
            XLWorkbook wb,
            string sheetName,
            string chartTitle,
            string[] seriesNames,
            System.Data.DataTable dt,
            Func<DataRow, (string label, double[] vals)> mapper)
        {
            var ws2 = wb.AddWorksheet(sheetName);

            ws2.Cell(1, 1).Value    = "Label";
            ws2.Cell(1, 1).Style.Font.Bold = true;
            for (int s = 0; s < seriesNames.Length; s++)
            {
                ws2.Cell(1, s + 2).Value    = seriesNames[s];
                ws2.Cell(1, s + 2).Style.Font.Bold = true;
            }

            var cats   = new List<string>();
            var values = Enumerable.Range(0, seriesNames.Length)
                                   .Select(_ => new List<double>())
                                   .ToArray();

            int r = 2;
            foreach (DataRow row in dt.Rows)
            {
                var (label, vals) = mapper(row);
                cats.Add(label);
                ws2.Cell(r, 1).Value = label;
                for (int s = 0; s < Math.Min(vals.Length, seriesNames.Length); s++)
                {
                    ws2.Cell(r, s + 2).Value = vals[s];
                    values[s].Add(vals[s]);
                }
                r++;
            }

            ws2.Columns().AdjustToContents();

            return new ChartInfo(
                sheetName,
                chartTitle,
                seriesNames,
                cats.ToArray(),
                values.Select(v => v.ToArray()).ToArray());
        }

        // ════════════════════════════════════════════════════════════════════
        //  OPENXML CHART INJECTION  (re-opens the .xlsx and injects DrawingML)
        // ════════════════════════════════════════════════════════════════════

        private static void InjectChart(string filePath, ChartInfo info)
        {
            if (info.Categories.Length == 0) return;

            using var doc  = SpreadsheetDocument.Open(filePath, isEditable: true);
            var wbPart     = doc.WorkbookPart!;

            var sheetEntry = wbPart.Workbook
                .Descendants<Sheet>()
                .FirstOrDefault(s => s.Name?.Value == info.SheetName);
            if (sheetEntry?.Id?.Value is null) return;

            var wsPart = (WorksheetPart)wbPart.GetPartById(sheetEntry.Id.Value);

            // ChartPart lives inside DrawingsPart
            var drawingsPart = wsPart.AddNewPart<DrawingsPart>();
            var chartPart    = drawingsPart.AddNewPart<ChartPart>();

            chartPart.ChartSpace = BuildBarChartSpace(info);
            chartPart.ChartSpace.Save();

            string chartRelId = drawingsPart.GetIdOfPart(chartPart);

            drawingsPart.WorksheetDrawing = BuildWorksheetDrawing(chartRelId);
            drawingsPart.WorksheetDrawing.Save();

            string drawingsRelId = wsPart.GetIdOfPart(drawingsPart);
            wsPart.Worksheet.Append(
                new DocumentFormat.OpenXml.Spreadsheet.Drawing { Id = drawingsRelId });
            wsPart.Worksheet.Save();
        }

        // ── DrawingML bar chart ──────────────────────────────────────────────

        private static C.ChartSpace BuildBarChartSpace(ChartInfo info)
        {
            var cs = new C.ChartSpace();
            cs.Append(new C.EditingLanguage { Val = "en-US" });

            var chart = new C.Chart();
            chart.Append(new C.AutoTitleDeleted { Val = false });
            chart.Append(MakeTitle(info.Title));

            var plotArea = new C.PlotArea();
            plotArea.Append(new C.Layout());

            var barChart = new C.BarChart();
            barChart.Append(new C.BarDirection { Val = C.BarDirectionValues.Column });
            barChart.Append(new C.BarGrouping  { Val = C.BarGroupingValues.Clustered });
            barChart.Append(new C.VaryColors   { Val = false });

            uint[] palette = { 0x1A3C5Eu, 0x2E86C1u, 0x28B463u, 0xE67E22u, 0x8E44ADu };

            for (int s = 0; s < info.SeriesNames.Length; s++)
            {
                var ser = new C.BarChartSeries();
                ser.Append(new C.Index { Val = (uint)s });
                ser.Append(new C.Order { Val = (uint)s });
                ser.Append(MakeSeriesText(info.SeriesNames[s]));
                ser.Append(MakeShapeProperties(palette[s % palette.Length]));
                ser.Append(MakeCategoryAxisData(info.Categories));
                ser.Append(MakeValues(info.Values[s]));
                barChart.Append(ser);
            }

            barChart.Append(new C.AxisId { Val = 100u });
            barChart.Append(new C.AxisId { Val = 200u });
            plotArea.Append(barChart);

            var catAxis = new C.CategoryAxis();
            catAxis.Append(new C.AxisId    { Val = 100u });
            catAxis.Append(new C.Scaling(new C.Orientation { Val = C.OrientationValues.MinMax }));
            catAxis.Append(new C.Delete    { Val = false });
            catAxis.Append(new C.AxisPosition { Val = C.AxisPositionValues.Bottom });
            catAxis.Append(new C.CrossingAxis  { Val = 200u });
            plotArea.Append(catAxis);

            var valAxis = new C.ValueAxis();
            valAxis.Append(new C.AxisId    { Val = 200u });
            valAxis.Append(new C.Scaling(new C.Orientation { Val = C.OrientationValues.MinMax }));
            valAxis.Append(new C.Delete    { Val = false });
            valAxis.Append(new C.AxisPosition { Val = C.AxisPositionValues.Left });
            valAxis.Append(new C.CrossingAxis  { Val = 100u });
            plotArea.Append(valAxis);

            chart.Append(plotArea);
            chart.Append(new C.Legend(new C.LegendPosition { Val = C.LegendPositionValues.Bottom }));
            chart.Append(new C.PlotVisibleOnly { Val = true });

            cs.Append(chart);
            return cs;
        }

        private static C.Title MakeTitle(string text)
        {
            var run = new A.Run();
            run.Append(new A.RunProperties { Language = "en-US", Bold = true });
            run.Append(new A.Text(text));

            var para = new A.Paragraph();
            para.Append(run);

            var rich = new C.RichText();
            rich.Append(new A.BodyProperties());
            rich.Append(new A.ListStyle());
            rich.Append(para);

            var tx = new C.ChartText();
            tx.Append(rich);

            var title = new C.Title();
            title.Append(tx);
            title.Append(new C.Overlay { Val = false });
            return title;
        }

        private static C.SeriesText MakeSeriesText(string name)
        {
            var cache = new C.StringCache();
            cache.Append(new C.PointCount { Val = 1u });
            cache.Append(new C.StringPoint { Index = 0u, NumericValue = new C.NumericValue(name) });

            var strRef = new C.StringReference();
            strRef.Append(new C.Formula($"\"{name}\""));
            strRef.Append(cache);

            var tx = new C.SeriesText();
            tx.Append(strRef);
            return tx;
        }

        private static C.ShapeProperties MakeShapeProperties(uint rgbHex)
        {
            var solidFill = new A.SolidFill();
            solidFill.Append(new A.RgbColorModelHex { Val = rgbHex.ToString("X6") });

            var spPr = new C.ShapeProperties();
            spPr.Append(solidFill);
            return spPr;
        }

        private static C.CategoryAxisData MakeCategoryAxisData(string[] cats)
        {
            var cache = new C.StringCache();
            cache.Append(new C.PointCount { Val = (uint)cats.Length });
            for (int i = 0; i < cats.Length; i++)
                cache.Append(new C.StringPoint
                {
                    Index        = (uint)i,
                    NumericValue = new C.NumericValue(cats[i])
                });

            var strRef = new C.StringReference();
            strRef.Append(new C.Formula("Sheet2!$A$2:$A$" + (cats.Length + 1)));
            strRef.Append(cache);

            var axData = new C.CategoryAxisData();
            axData.Append(strRef);
            return axData;
        }

        private static C.Values MakeValues(double[] vals)
        {
            var cache = new C.NumberingCache();
            cache.Append(new C.FormatCode("General"));
            cache.Append(new C.PointCount { Val = (uint)vals.Length });
            for (int i = 0; i < vals.Length; i++)
                cache.Append(new C.NumericPoint
                {
                    Index        = (uint)i,
                    NumericValue = new C.NumericValue(vals[i].ToString("G"))
                });

            var numRef = new C.NumberReference();
            numRef.Append(new C.Formula("Sheet2!$B$2:$B$" + (vals.Length + 1)));
            numRef.Append(cache);

            var v = new C.Values();
            v.Append(numRef);
            return v;
        }

        // ── Worksheet drawing (anchors chart on the sheet) ───────────────────

        private static XDr.WorksheetDrawing BuildWorksheetDrawing(string chartRelId)
        {
            var anchor = new XDr.TwoCellAnchor();

            anchor.Append(new XDr.FromMarker(
                new XDr.ColumnId("0"),  new XDr.ColumnOffset("0"),
                new XDr.RowId("3"),    new XDr.RowOffset("0")));
            anchor.Append(new XDr.ToMarker(
                new XDr.ColumnId("10"), new XDr.ColumnOffset("0"),
                new XDr.RowId("25"),   new XDr.RowOffset("0")));

            var nvProps = new XDr.NonVisualGraphicFrameProperties(
                new XDr.NonVisualDrawingProperties { Id = 2u, Name = "Chart 1" },
                new XDr.NonVisualGraphicFrameDrawingProperties());

            var xfrm = new XDr.Transform(
                new A.Offset  { X = 0L, Y = 0L },
                new A.Extents { Cx = 0L, Cy = 0L });

            var graphicData = new A.GraphicData
            {
                Uri = "http://schemas.openxmlformats.org/drawingml/2006/chart"
            };
            graphicData.Append(new C.ChartReference { Id = chartRelId });

            var graphic = new A.Graphic();
            graphic.Append(graphicData);

            var frame = new XDr.GraphicFrame();
            frame.Append(nvProps);
            frame.Append(xfrm);
            frame.Append(graphic);

            anchor.Append(frame);
            anchor.Append(new XDr.ClientData());

            var wd = new XDr.WorksheetDrawing();
            wd.Append(anchor);
            return wd;
        }
    }
}
